// <auto-generated />
using System;
using ControlFinance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlFinance.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208071304_AddPrevisaoCompra")]
    partial class AddPrevisaoCompra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlFinance.Domain.Entities.AnaliseMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<decimal>("GastosFixos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gastos_fixos");

                    b.Property<decimal>("GastosVariaveis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gastos_variaveis");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_gastos");

                    b.Property<decimal>("TotalParcelas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("TotalReceitas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_receitas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "MesReferencia")
                        .IsUnique();

                    b.ToTable("analises_mensais", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cartoes_credito", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<bool>("Padrao")
                        .HasColumnType("boolean")
                        .HasColumnName("padrao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CodigoVerificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("codigos_verificacao", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoCreditoId")
                        .HasColumnType("integer")
                        .HasColumnName("cartao_credito_id");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fechamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId", "MesReferencia")
                        .IsUnique();

                    b.ToTable("faturas", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer")
                        .HasColumnName("fatura_id");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lancamento_id");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<bool>("Paga")
                        .HasColumnType("boolean")
                        .HasColumnName("paga");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.HasIndex("LancamentoId");

                    b.ToTable("parcelas", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("Confianca")
                        .HasColumnType("integer")
                        .HasColumnName("confianca");

                    b.Property<int>("DiasDeHistorico")
                        .HasColumnType("integer")
                        .HasColumnName("dias_de_historico");

                    b.Property<decimal>("GastoFixoEstimado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_fixo_estimado");

                    b.Property<decimal>("GastoMensalMedio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_mensal_medio");

                    b.Property<decimal>("GastoVariavelEstimado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_variavel_estimado");

                    b.Property<int>("MesesComDados")
                        .HasColumnType("integer")
                        .HasColumnName("meses_com_dados");

                    b.Property<int>("QuantidadeParcelasAbertas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas_abertas");

                    b.Property<decimal>("ReceitaMensalMedia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("receita_mensal_media");

                    b.Property<bool>("Sujo")
                        .HasColumnType("boolean")
                        .HasColumnName("sujo");

                    b.Property<decimal>("TotalParcelasAbertas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_parcelas_abertas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("VolatilidadeGastos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("volatilidade_gastos");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfis_financeiros", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartaoCreditoId")
                        .HasColumnType("integer")
                        .HasColumnName("cartao_credito_id");

                    b.Property<int>("Confianca")
                        .HasColumnType("integer")
                        .HasColumnName("confianca");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prevista");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("FolgaMensalMedia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("folga_mensal_media");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<decimal>("MenorSaldoProjetado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("menor_saldo_projetado");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<string>("PiorMes")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pior_mes");

                    b.Property<int>("Recomendacao")
                        .HasColumnType("integer")
                        .HasColumnName("recomendacao");

                    b.Property<int>("Risco")
                        .HasColumnType("integer")
                        .HasColumnName("risco");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("simulacoes_compra", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompraMes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompromissosExistentes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compromissos_existentes");

                    b.Property<decimal>("GastoPrevisto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_previsto");

                    b.Property<decimal>("ImpactoCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("impacto_compra");

                    b.Property<decimal>("ImpactoPercentual")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("impacto_percentual");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<decimal>("ReceitaPrevista")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("receita_prevista");

                    b.Property<decimal>("SaldoBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_base");

                    b.Property<decimal>("SaldoComCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_com_compra");

                    b.Property<int>("SimulacaoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("simulacao_compra_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoCompraId");

                    b.ToTable("simulacoes_compra_meses", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<bool>("TelegramVinculado")
                        .HasColumnType("boolean")
                        .HasColumnName("telegram_vinculado");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.AnaliseMensal", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AnalisesMensais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CartaoCredito", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cartoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CodigoVerificacao", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("CodigosVerificacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Faturas")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Lancamento", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Parcelas")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Lancamento", "Lancamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilFinanceiro")
                        .HasForeignKey("ControlFinance.Domain.Entities.PerfilFinanceiro", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompra", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SimulacoesCompra")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompraMes", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.SimulacaoCompra", "SimulacaoCompra")
                        .WithMany("Meses")
                        .HasForeignKey("SimulacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoCompra");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CartaoCredito", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Lancamento", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompra", b =>
                {
                    b.Navigation("Meses");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AnalisesMensais");

                    b.Navigation("Cartoes");

                    b.Navigation("Categorias");

                    b.Navigation("CodigosVerificacao");

                    b.Navigation("Lancamentos");

                    b.Navigation("PerfilFinanceiro");

                    b.Navigation("SimulacoesCompra");
                });
#pragma warning restore 612, 618
        }
    }
}
