// <auto-generated />
using System;
using ControlFinance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlFinance.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218223708_AddDuracaoAcessoConvite")]
    partial class AddDuracaoAcessoConvite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlFinance.Domain.Entities.AjusteLimiteCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoId")
                        .HasColumnType("integer")
                        .HasColumnName("cartao_id");

                    b.Property<DateTime>("DataAjuste")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ajuste");

                    b.Property<decimal>("NovoLimiteTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("novo_limite_total");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("percentual");

                    b.Property<decimal>("ValorAcrescimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_acrescimo");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_base");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("ajustes_limite_cartao", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.AnaliseMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<decimal>("GastosFixos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gastos_fixos");

                    b.Property<decimal>("GastosVariaveis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gastos_variaveis");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_gastos");

                    b.Property<decimal>("TotalParcelas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("TotalReceitas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_receitas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "MesReferencia")
                        .IsUnique();

                    b.ToTable("analises_mensais", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("integer");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite");

                    b.Property<decimal>("LimiteBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite_base");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cartoes_credito", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<bool>("Padrao")
                        .HasColumnType("boolean")
                        .HasColumnName("padrao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CodigoConvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DuracaoAcessoDias")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_acesso_dias");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<int?>("UsadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usado_por_usuario_id");

                    b.Property<int?>("UsoMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("uso_maximo");

                    b.Property<int>("UsosRealizados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usos_realizados");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("UsadoPorUsuarioId");

                    b.ToTable("codigos_convite", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CodigoVerificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("codigos_verificacao", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.ConversaPendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DadosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dados_json");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("ExpiraEm");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conversas_pendentes", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.EventoSazonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<bool>("DetectadoAutomaticamente")
                        .HasColumnType("boolean")
                        .HasColumnName("detectado_automaticamente");

                    b.Property<bool>("EhReceita")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_receita");

                    b.Property<int>("MesOcorrencia")
                        .HasColumnType("integer")
                        .HasColumnName("mes_ocorrencia");

                    b.Property<bool>("RecorrenteAnual")
                        .HasColumnType("boolean")
                        .HasColumnName("recorrente_anual");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorMedio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_medio");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId", "MesOcorrencia");

                    b.ToTable("eventos_sazonais", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoCreditoId")
                        .HasColumnType("integer")
                        .HasColumnName("cartao_credito_id");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fechamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId", "MesReferencia")
                        .IsUnique();

                    b.ToTable("faturas", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_lancamentos_categoria");

                    b.HasIndex("UsuarioId", "Data")
                        .HasDatabaseName("IX_lancamentos_usuario_data");

                    b.HasIndex("UsuarioId", "Tipo", "Data")
                        .HasDatabaseName("IX_lancamentos_usuario_tipo_data");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LembretePagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataFimRecorrencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DiaRecorrente")
                        .HasColumnType("integer")
                        .HasColumnName("dia_recorrente");

                    b.Property<int?>("DiaSemanaRecorrente")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana_recorrente");

                    b.Property<int>("DiasAntecedenciaLembrete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("dias_antecedencia_lembrete");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Frequencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequencia");

                    b.Property<TimeSpan>("HorarioFimLembrete")
                        .HasColumnType("interval")
                        .HasColumnName("horario_fim_lembrete");

                    b.Property<TimeSpan>("HorarioInicioLembrete")
                        .HasColumnType("interval")
                        .HasColumnName("horario_inicio_lembrete");

                    b.Property<bool>("LembreteTelegramAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("lembrete_telegram_ativo");

                    b.Property<string>("PeriodKeyAtual")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period_key_atual");

                    b.Property<bool>("RecorrenteMensal")
                        .HasColumnType("boolean")
                        .HasColumnName("recorrente_mensal");

                    b.Property<DateTime?>("UltimoEnvioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_envio_em");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("UsuarioId", "Ativo");

                    b.ToTable("lembretes_pagamento", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LimiteCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorLimite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_limite");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("limites_categoria", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LogDecisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("EntradasJson")
                        .HasColumnType("text")
                        .HasColumnName("entradas_json");

                    b.Property<string>("JustificativaResumida")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justificativa_resumida");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resultado");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs_decisao", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LogLembreteTelegram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("Erro")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("erro");

                    b.Property<int>("LembretePagamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lembrete_pagamento_id");

                    b.Property<long?>("MensagemTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("mensagem_telegram_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoLembrete")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_lembrete");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoEm");

                    b.HasIndex("LembretePagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs_lembrete_telegram", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.MetaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_alvo");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_atual");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("metas_financeiras", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.NotificacaoEnviada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_referencia");

                    b.Property<DateTime>("EnviadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_em");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Chave", "DataReferencia");

                    b.HasIndex("Chave", "UsuarioId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("notificacoes_enviadas", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PagamentoCiclo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<int>("LembretePagamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lembrete_pagamento_id");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean")
                        .HasColumnName("pago");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period_key");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id");

                    b.HasIndex("LembretePagamentoId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("pagamentos_ciclo", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer")
                        .HasColumnName("fatura_id");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lancamento_id");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<bool>("Paga")
                        .HasColumnType("boolean")
                        .HasColumnName("paga");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.HasIndex("LancamentoId");

                    b.ToTable("parcelas", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PerfilComportamental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CategoriaMaisFrequente")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria_mais_frequente");

                    b.Property<int>("ComprasNaoPlanejadas30d")
                        .HasColumnType("integer")
                        .HasColumnName("compras_nao_planejadas_30d");

                    b.Property<decimal>("ComprometimentoRendaPercentual")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("comprometimento_renda_percentual");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("FormaPagamentoPreferida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento_preferida");

                    b.Property<int>("FrequenciaDuvidaGasto")
                        .HasColumnType("integer")
                        .HasColumnName("frequencia_duvida_gasto");

                    b.Property<int>("MesesComSaldoNegativo")
                        .HasColumnType("integer")
                        .HasColumnName("meses_com_saldo_negativo");

                    b.Property<int>("NivelImpulsividade")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_impulsividade");

                    b.Property<string>("PadraoMensalDetectado")
                        .HasColumnType("text")
                        .HasColumnName("padrao_mensal_detectado");

                    b.Property<decimal>("ScoreEstabilidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("score_estabilidade");

                    b.Property<DateTime>("ScoreSaudeAtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("score_saude_atualizado_em");

                    b.Property<string>("ScoreSaudeDetalhes")
                        .HasColumnType("text")
                        .HasColumnName("score_saude_detalhes");

                    b.Property<decimal>("ScoreSaudeFinanceira")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("score_saude_financeira");

                    b.Property<decimal>("TendenciaCrescimentoGastos")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("tendencia_crescimento_gastos");

                    b.Property<int>("ToleranciaRisco")
                        .HasColumnType("integer")
                        .HasColumnName("tolerancia_risco");

                    b.Property<int>("TotalConsultasDecisao")
                        .HasColumnType("integer")
                        .HasColumnName("total_consultas_decisao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfis_comportamentais", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("Confianca")
                        .HasColumnType("integer")
                        .HasColumnName("confianca");

                    b.Property<int>("DiasDeHistorico")
                        .HasColumnType("integer")
                        .HasColumnName("dias_de_historico");

                    b.Property<decimal>("GastoFixoEstimado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_fixo_estimado");

                    b.Property<decimal>("GastoMensalMedio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_mensal_medio");

                    b.Property<decimal>("GastoVariavelEstimado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_variavel_estimado");

                    b.Property<int>("MesesComDados")
                        .HasColumnType("integer")
                        .HasColumnName("meses_com_dados");

                    b.Property<int>("QuantidadeParcelasAbertas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas_abertas");

                    b.Property<decimal>("ReceitaMensalMedia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("receita_mensal_media");

                    b.Property<bool>("Sujo")
                        .HasColumnType("boolean")
                        .HasColumnName("sujo");

                    b.Property<decimal>("TotalParcelasAbertas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_parcelas_abertas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("VolatilidadeGastos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("volatilidade_gastos");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfis_financeiros", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("IpCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ip_criacao");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("jwt_id");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean")
                        .HasColumnName("revogado");

                    b.Property<string>("SubstituidoPor")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("substituido_por");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("token");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.RegistroPendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoConvite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_convite");

                    b.Property<string>("CodigoVerificacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("codigo_verificacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<int>("TentativasVerificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_verificacao");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("registros_pendentes", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartaoCreditoId")
                        .HasColumnType("integer")
                        .HasColumnName("cartao_credito_id");

                    b.Property<int>("Confianca")
                        .HasColumnType("integer")
                        .HasColumnName("confianca");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prevista");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("FolgaMensalMedia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("folga_mensal_media");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<decimal>("MenorSaldoProjetado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("menor_saldo_projetado");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<string>("PiorMes")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pior_mes");

                    b.Property<int>("Recomendacao")
                        .HasColumnType("integer")
                        .HasColumnName("recomendacao");

                    b.Property<int>("Risco")
                        .HasColumnType("integer")
                        .HasColumnName("risco");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("simulacoes_compra", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompraMes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompromissosExistentes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compromissos_existentes");

                    b.Property<decimal>("GastoPrevisto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gasto_previsto");

                    b.Property<decimal>("ImpactoCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("impacto_compra");

                    b.Property<decimal>("ImpactoPercentual")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("impacto_percentual");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<decimal>("ReceitaPrevista")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("receita_prevista");

                    b.Property<decimal>("SaldoBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_base");

                    b.Property<decimal>("SaldoComCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_com_compra");

                    b.Property<int>("SimulacaoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("simulacao_compra_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoCompraId");

                    b.ToTable("simulacoes_compra_meses", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.TagLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("UsuarioId", "Nome");

                    b.ToTable("tags_lancamento", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcessoExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acesso_expira_em");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<bool>("TelegramVinculado")
                        .HasColumnType("boolean")
                        .HasColumnName("telegram_vinculado");

                    b.Property<int>("TentativasLoginFalhadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_login_falhadas");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.AjusteLimiteCartao", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.CartaoCredito", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.AnaliseMensal", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AnalisesMensais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CartaoCredito", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cartoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CodigoConvite", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "UsadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("UsadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("UsadoPorUsuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CodigoVerificacao", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("CodigosVerificacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.ConversaPendente", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.EventoSazonal", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("EventosSazonais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Faturas")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Lancamento", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LembretePagamento", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LembretesPagamento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LimiteCategoria", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Limites")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LimitesCategoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LogDecisao", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LogLembreteTelegram", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.LembretePagamento", "LembretePagamento")
                        .WithMany("LogsLembrete")
                        .HasForeignKey("LembretePagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LembretePagamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.MetaFinanceira", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MetasFinanceiras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.NotificacaoEnviada", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PagamentoCiclo", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.LembretePagamento", "LembretePagamento")
                        .WithMany("PagamentosCiclo")
                        .HasForeignKey("LembretePagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LembretePagamento");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Parcelas")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Lancamento", "Lancamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PerfilComportamental", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilComportamental")
                        .HasForeignKey("ControlFinance.Domain.Entities.PerfilComportamental", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.PerfilFinanceiro", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilFinanceiro")
                        .HasForeignKey("ControlFinance.Domain.Entities.PerfilFinanceiro", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompra", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SimulacoesCompra")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompraMes", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.SimulacaoCompra", "SimulacaoCompra")
                        .WithMany("Meses")
                        .HasForeignKey("SimulacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoCompra");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.TagLancamento", b =>
                {
                    b.HasOne("ControlFinance.Domain.Entities.Lancamento", "Lancamento")
                        .WithMany("Tags")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lancamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.CartaoCredito", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Limites");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Lancamento", b =>
                {
                    b.Navigation("Parcelas");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.LembretePagamento", b =>
                {
                    b.Navigation("LogsLembrete");

                    b.Navigation("PagamentosCiclo");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.SimulacaoCompra", b =>
                {
                    b.Navigation("Meses");
                });

            modelBuilder.Entity("ControlFinance.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AnalisesMensais");

                    b.Navigation("Cartoes");

                    b.Navigation("Categorias");

                    b.Navigation("CodigosVerificacao");

                    b.Navigation("EventosSazonais");

                    b.Navigation("Lancamentos");

                    b.Navigation("LembretesPagamento");

                    b.Navigation("LimitesCategoria");

                    b.Navigation("MetasFinanceiras");

                    b.Navigation("PerfilComportamental");

                    b.Navigation("PerfilFinanceiro");

                    b.Navigation("SimulacoesCompra");
                });
#pragma warning restore 612, 618
        }
    }
}
